[package]
name = "tokio-rustls"
version = "0.7.1"
authors = ["quininer kel <quininer@live.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/quininer/tokio-rustls"
homepage = "https://github.com/quininer/tokio-rustls"
documentation = "https://docs.rs/tokio-rustls"
readme = "README.md"
description = "Asynchronous TLS/SSL streams for Tokio using Rustls."
categories = ["asynchronous", "cryptography", "network-programming"]

[badges]
travis-ci = { repository = "quininer/tokio-rustls" }
appveyor = { repository = "quininer/tokio-rustls" }

[dependencies]
futures-core = { version = "0.2.0", optional = true }
futures-io = { version = "0.2.0", optional = true }
tokio = { version = "0.1.6", optional = true }
rustls = "0.13"
webpki = "0.18.1"
log = "0.4"

[dev-dependencies]
# futures = "0.2.0"
tokio = "0.1.6"

[features]
default = [ "tokio" ]
# unstable-futures = [
# 	"futures-core",
# 	"futures-io",
# 	"tokio/unstable-futures"
# ]
